erp/erp/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('', include('erp_core.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# custom admin page
admin.site.site_header = "ERP Admin Page"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "Welcome to ERP Admin Portal"

erp/erp_core/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from rest_framework import routers

from . import views

app_name = 'erp_core'

router = routers.DefaultRouter()
router.register(r'company', views.CompanyViewSet)
router.register(r'product', views.ProductViewSet)
router.register(r'invoice', views.InvoiceViewSet)
router.register(r'payment', views.PaymentViewSet)

urlpatterns = [
    path('', login_required(views.Home.as_view()), name='home'),
    path('api/v1/', include(router.urls), name='api_v1'),
    path('help/', views.Help.as_view(), name='help'),
    path('feature/', views.Feature.as_view(), name='feature'),
    path('login/', auth_views.LoginView.as_view(template_name='erp_core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='erp_core/logout.html'), name='logout'),
    path('company_create/', login_required(views.CompanyCreate.as_view()), name='company_create'),
    path('company_list/', login_required(views.CompanyList.as_view()), name='company_list'),
    path('company_detail/<slug:slug>/', login_required(views.CompanyDetail.as_view()), name='company_detail'),
    path('company_update/<int:pk>/', login_required(views.CompanyUpdate.as_view()), name='company_update'),
    path('company_clone/<int:pk>/', login_required(views.CompanyClone.as_view()), name='company_clone'),
    path('product_create/', login_required(views.ProductCreate.as_view()), name='product_create'),
    path('product_list/', login_required(views.ProductList.as_view()), name='product_list'),
    path('product_detail/<int:pk>/', login_required(views.ProductDetail.as_view()), name='product_detail'),
    path('product_update/<int:pk>/', login_required(views.ProductUpdate.as_view()), name='product_update'),
    path('product_clone/<int:pk>/', login_required(views.ProductClone.as_view()), name='product_clone'),
    path('invoice_create/', login_required(views.InvoiceCreate.as_view()), name='invoice_create'),
    path('invoice_list/', login_required(views.InvoiceList.as_view()), name='invoice_list'),
    path('invoice_update/<int:pk>/', login_required(views.InvoiceUpdate.as_view()), name='invoice_update'),
    path('invoice_clone/<int:pk>/', login_required(views.InvoiceClone.as_view()), name='invoice_clone'),
    path('payment_create/', login_required(views.PaymentCreate.as_view()), name='payment_create'),
    path('payment_list/', login_required(views.PaymentList.as_view()), name='payment_list'),
    path('payment_update/<int:pk>/', login_required(views.PaymentUpdate.as_view()), name='payment_update'),
    path('payment_clone/<int:pk>/', login_required(views.PaymentClone.as_view()), name='payment_clone'),
    path('filtered_view/', login_required(views.FilteredView.as_view()), name='filtered_view'),
    path('filtered_view/invoice_active/', login_required(views.InvoiceActive.as_view()), name='invoice_active'),
    path('filtered_view/invoice_active_overdue/', login_required(views.InvoiceActiveOverdue.as_view()), name='invoice_active_overdue'),
    path('filtered_view/invoice_passive/', login_required(views.InvoicePassive.as_view()), name='invoice_passive'),
    path('filtered_view/invoice_passive_overdue/', login_required(views.InvoicePassiveOverdue.as_view()), name='invoice_passive_overdue'),
    path('filtered_view/payment_active/', login_required(views.PaymentActive.as_view()), name='payment_active'),
    path('filtered_view/payment_passive/', login_required(views.PaymentPassive.as_view()), name='payment_passive'),
    path('filtered_view/check_active/', login_required(views.CheckActive.as_view()), name='check_active'),
    path('filtered_view/check_passive/', login_required(views.CheckPassive.as_view()), name='check_passive'),
    path('csv_export/', login_required(views.CsvExport.as_view()), name='csv_export'),
]

erp/erp_core/views.py
import csv

from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from rest_framework import permissions, viewsets

from . import models, forms, filters, functions, serializers


# GENERAL WEBSITE NAVIGATION

class Home(View):
    def get(self, request):
        return render(request, 'erp_core/home.html')
    
    
class Help(View):
    """Help page"""
    template_name = 'erp_core/help.html'
    
    def get(self, request):
        return render(request, self.template_name)
    

class Feature(View):
    """Feature page"""
    template_name = 'erp_core/feature.html'
    
    def get(self, request):
        return render(request, self.template_name)
        
        
# COMPANY MANAGEMENT 

class CompanyCreate(CreateView):
    """Create a new company"""
    model = models.Company
    form_class = forms.CompanyForm
    success_url = reverse_lazy('erp_core:company_list') 
    
    
class CompanyDetail(DetailView):
    """View a single profile"""
    model = models.Company
    slug_field = 'vat_id'
    
    
class CompanyList(ListView):
    """View all profiles"""
    model = models.Company
    
    # filter via query
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = filters.CompanyFilter(self.request.GET, queryset=self.get_queryset())
        return context
    
    
class CompanyUpdate(UpdateView):
    """Update a company"""
    model = models.Company
    form_class = forms.CompanyForm
    success_url = reverse_lazy('erp_core:company_list')
    
    
class CompanyClone(CreateView):
    """Get object desired from url with record.id and override the object context with it.
    """
    model = models.Company
    form_class = forms.CompanyForm
    success_url = reverse_lazy('erp_core:company_list')
    template_name = 'erp_core/company_clone.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.name = f"{self.object.name}_CLONE"
        self.object.vat_id = 0
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)
    
    
# PRODUCT MANAGEMENT

class ProductCreate(CreateView):
    """Create a new product"""
    model = models.Product
    form_class = forms.ProductForm
    success_url = reverse_lazy('erp_core:product_list') 
    
    
class ProductDetail(DetailView):
    """View a single product"""
    model = models.Product
    slug_field = 'id'
    
    
class ProductList(ListView):
    """View all profiles"""
    model = models.Product
    
    # filter via query
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = filters.ProductFilter(self.request.GET, queryset=self.get_queryset())
        return context
    
    
class ProductUpdate(UpdateView):
    """Update a product"""
    model = models.Product
    form_class = forms.ProductForm
    success_url = reverse_lazy('erp_core:product_list')
    
    
class ProductClone(CreateView):
    """Get object desired from url with record.id and override the object context with it.
    """
    model = models.Product
    form_class = forms.ProductForm
    success_url = reverse_lazy('erp_core:product_list')
    template_name = 'erp_core/product_clone.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.name = f"{self.object.name}_CLONE"
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


# INVOICE MANAGEMENT
    
class InvoiceCreate(CreateView):
    """Create a new invoice"""
    model = models.Invoice
    form_class = forms.InvoiceForm
    success_url = reverse_lazy('erp_core:invoice_list') 
    
    
class InvoiceList(ListView):
    """View all invoices"""
    model = models.Invoice   
        
    # filter via query
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = filters.InvoiceFilter(self.request.GET, queryset=self.get_queryset())
        return context  
    
    
class InvoiceUpdate(UpdateView):
    """Update an invoice"""
    model = models.Invoice
    form_class = forms.InvoiceForm
    success_url = reverse_lazy('erp_core:invoice_list')
    

class InvoiceClone(CreateView):
    """Get object desired from url with record.id and override the object context with it.
    """
    model = models.Invoice
    form_class = forms.InvoiceForm
    success_url = reverse_lazy('erp_core:invoice_list')
    template_name = 'erp_core/invoice_clone.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)
    
    
# PAYMENT MANAGEMENT

class PaymentCreate(CreateView):
    """Create a new payment"""
    model = models.Payment
    form_class = forms.PaymentForm
    success_url = reverse_lazy('erp_core:payment_list') 
    
    
class PaymentList(ListView):
    """View all Payments"""
    model = models.Payment
    
    # filter via query
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = filters.PaymentFilter(self.request.GET, queryset=self.get_queryset())
        return context  
    
    
class PaymentUpdate(UpdateView):
    """Update an Payment"""
    model = models.Payment
    form_class = forms.PaymentForm
    success_url = reverse_lazy('erp_core:payment_list')
    
    
class PaymentClone(CreateView):
    """Get object desired from url with record.id and override the object context with it.
    """
    model = models.Payment
    form_class = forms.PaymentForm
    success_url = reverse_lazy('erp_core:payment_list')
    template_name = 'erp_core/payment_clone.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)
    
    
# PRE-MADE FILTERS

class FilteredView(View):
    """Main page for all the filters"""
    def get(self, request):
        return render(request, 'erp_core/filtered_view.html')


class InvoiceActive(View):
    """Pre-made filter for active invoices"""
    model = models.Invoice
    template_name = 'erp_core/invoice_active.html'
    
    def get(self, request):
        context = self.model.objects.all().filter(kind='ACTIVE')
        return render(request, self.template_name, {'context': context})
    
    
class InvoiceActiveOverdue(View):
    """Pre-made filter for overdue active invoices"""
    model = models.Invoice
    template_name = 'erp_core/invoice_active_overdue.html'
    
    def get(self, request):
        context = self.model.objects.all().filter(kind='ACTIVE', status='UNPAID')
        return render(request, self.template_name, {'context': context})


class InvoicePassive(View):
    """Pre-made filter for passive invoices"""
    model = models.Invoice
    template_name = 'erp_core/invoice_passive.html'
    
    def get(self, request):
        context = self.model.objects.all().filter(kind='PASSIVE')
        return render(request, self.template_name, {'context': context}) 
    
    
class InvoicePassiveOverdue(View):
    """Pre-made filter for overdue active invoices"""
    model = models.Invoice
    template_name = 'erp_core/invoice_passive_overdue.html'
    
    def get(self, request):
        context = self.model.objects.all().filter(kind='PASSIVE', status='UNPAID')
        return render(request, self.template_name, {'context': context})
    
    
class PaymentActive(View):
    """Pre-made filter for active payments"""
    model = models.Payment
    template_name = 'erp_core/payment_active.html'
    
    def get(self, request):
        context = self.model.objects.all().filter(kind='ACTIVE')
        return render(request, self.template_name, {'context': context})


class PaymentPassive(View):
    """Pre-made filter for passive payments"""
    model = models.Payment
    template_name = 'erp_core/payment_passive.html'
    
    def get(self, request):
        context = self.model.objects.all().filter(kind='PASSIVE')
        return render(request, self.template_name, {'context': context})    


# CREDIT MANAGEMENT

class CheckActive(View):
    """View to show the credit balance"""
    template_name = 'erp_core/check_active.html'
    
    def get(self, request):
        context = functions.credit_calculator('ACTIVE')
        return render(request, self.template_name, {'context': context})
    
    
class CheckPassive(View):
    """View to show the credit balance"""
    template_name = 'erp_core/check_passive.html'
    
    def get(self, request):
        context = functions.credit_calculator('PASSIVE')
        return render(request, self.template_name, {'context': context})


# CSV EXPORT

class CsvExport(View):
    """Generate a csv file of the context object"""
    template_name = 'erp_core/csv_export.html'
    
    def get(self, request) -> csv:
        response = HttpResponse(
            content_type='text/csv',
            headers={'Content-Disposition':'attachment; filename="csv_detail.csv"'},
        )
        
        # this allows to scale on many other CSV export just managing the url param
        if 'invoice' in self.request.GET:
            model = models.Invoice.objects.all().values()
        elif 'company' in self.request.GET:
            model = models.Company.objects.all().values()
        elif 'product' in self.request.GET:
            model = models.Product.objects.all().values()
        else:
            raise Http404
        
        writer = csv.writer(response)
        
        for item in model:
            writer.writerow([item])

erp/erp_core/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block title %}
    <title>Home Page</title>
    {% endblock %}
    
    <!-- FAVICON -->
    <link rel="icon" href="{% static 'erp_core/img/favicon.ico' %}">

    <!-- CUSTOM CSS -->
    <link rel="stylesheet" href="{% static 'erp_core/css/stylesheet.css' %}">

    <!-- BOOTSTRAP CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
 
    <!-- FONT AWESOME -->
    <script src="https://kit.fontawesome.com/d721e6a14c.js" crossorigin="anonymous"></script>

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <a class="navbar-brand text-light m-4" href="{% url 'erp_core:home' %}">
            <h2><i class="fa-solid fa-meteor"></i>&nbsp;</i>sERPent</h2>
            <h6 class="text-light small">Python ERP prototype </h6>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="" role="button" ><i class="fa fa-bars" aria-hidden="true" style="color:#ffffff"></i></span>
        </button>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'erp_core:company_create' %}">+New Co</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'erp_core:invoice_create' %}">+New Inv</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'erp_core:payment_create' %}">+New Pay</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'erp_core:product_create' %}">+New Prod</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'erp_core:filtered_view' %}">Pre-Made Filters</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'erp_core:feature' %}">Alpha Feats</a>
                </li>
            </ul>

            {% if user.is_authenticated %}
                <ul class="navbar-nav ms-auto">
                    <div class="dropdown">
                        <a class="btn btn-info text-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        Welcome, {{ user.username }}
                        </a>
                    
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="/help/">Help</a></li>
                        <li><a class="dropdown-item" href="/admin/">Admin Panel</a></li>
                        <li><a class="dropdown-item" href="/api/v1/">Web APIs</a></li>
                        <li><a class="dropdown-item" href="/logout/">Logout</a></li>
                        </ul>
                    </div>
                </ul>
            {% endif %}
        </div>
    </nav> 

    {% block content %}
    {% endblock %}
    
</body>
</html>