erp/erp/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('', include('erp_core.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# custom admin page
admin.site.site_header = "ERP Admin Page"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "Welcome to ERP Admin Portal"

erp/erp_core/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from rest_framework import routers

from . import views

app_name = 'erp_core'

router = routers.DefaultRouter()
router.register(r'company', views.CompanyViewSet)
router.register(r'product', views.ProductViewSet)
router.register(r'invoice', views.InvoiceViewSet)
router.register(r'payment', views.PaymentViewSet)

urlpatterns = [
    path('', login_required(views.Home.as_view()), name='home'),
    path('api/v1/', include(router.urls), name='api_v1'),
    path('help/', views.Help.as_view(), name='help'),
    path('feature/', views.Feature.as_view(), name='feature'),
    path('login/', auth_views.LoginView.as_view(template_name='erp_core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='erp_core/logout.html'), name='logout'),
    path('company_create/', login_required(views.CompanyCreate.as_view()), name='company_create'),
    path('company_list/', login_required(views.CompanyList.as_view()), name='company_list'),
    path('company_detail/<slug:slug>/', login_required(views.CompanyDetail.as_view()), name='company_detail'),
    path('company_update/<int:pk>/', login_required(views.CompanyUpdate.as_view()), name='company_update'),
    path('company_clone/<int:pk>/', login_required(views.CompanyClone.as_view()), name='company_clone'),
    path('product_create/', login_required(views.ProductCreate.as_view()), name='product_create'),
    path('product_list/', login_required(views.ProductList.as_view()), name='product_list'),
    path('product_detail/<int:pk>/', login_required(views.ProductDetail.as_view()), name='product_detail'),
    path('product_update/<int:pk>/', login_required(views.ProductUpdate.as_view()), name='product_update'),
    path('product_clone/<int:pk>/', login_required(views.ProductClone.as_view()), name='product_clone'),
    path('invoice_create/', login_required(views.InvoiceCreate.as_view()), name='invoice_create'),
    path('invoice_list/', login_required(views.InvoiceList.as_view()), name='invoice_list'),
    path('invoice_update/<int:pk>/', login_required(views.InvoiceUpdate.as_view()), name='invoice_update'),
    path('invoice_clone/<int:pk>/', login_required(views.InvoiceClone.as_view()), name='invoice_clone'),
    path('payment_create/', login_required(views.PaymentCreate.as_view()), name='payment_create'),
    path('payment_list/', login_required(views.PaymentList.as_view()), name='payment_list'),
    path('payment_update/<int:pk>/', login_required(views.PaymentUpdate.as_view()), name='payment_update'),
    path('payment_clone/<int:pk>/', login_required(views.PaymentClone.as_view()), name='payment_clone'),
    path('filtered_view/', login_required(views.FilteredView.as_view()), name='filtered_view'),
    path('filtered_view/invoice_active/', login_required(views.InvoiceActive.as_view()), name='invoice_active'),
    path('filtered_view/invoice_active_overdue/', login_required(views.InvoiceActiveOverdue.as_view()), name='invoice_active_overdue'),
    path('filtered_view/invoice_passive/', login_required(views.InvoicePassive.as_view()), name='invoice_passive'),
    path('filtered_view/invoice_passive_overdue/', login_required(views.InvoicePassiveOverdue.as_view()), name='invoice_passive_overdue'),
    path('filtered_view/payment_active/', login_required(views.PaymentActive.as_view()), name='payment_active'),
    path('filtered_view/payment_passive/', login_required(views.PaymentPassive.as_view()), name='payment_passive'),
    path('filtered_view/check_active/', login_required(views.CheckActive.as_view()), name='check_active'),
    path('filtered_view/check_passive/', login_required(views.CheckPassive.as_view()), name='check_passive'),
    path('csv_export/', login_required(views.CsvExport.as_view()), name='csv_export'),
]

erp/erp_core/views.py
import csv

from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from rest_framework import permissions, viewsets

from . import models, forms, filters, functions, serializers


# GENERAL WEBSITE NAVIGATION

class Home(View):
    def get(self, request):
        return render(request, 'erp_core/home.html')
    
    
class Help(View):
    """Help page"""
    template_name = 'erp_core/help.html'
    
    def get(self, request):
        return render(request, self.template_name)
    

class Feature(View):
    """Feature page"""
    template_name = 'erp_core/feature.html'
    
    def get(self, request):
        return render(request, self.template_name)
        
        
# COMPANY MANAGEMENT 

class CompanyCreate(CreateView):
    """Create a new company"""
    model = models.Company
    form_class = forms.CompanyForm
    success_url = reverse_lazy('erp_core:company_list') 
    
    
class CompanyDetail(DetailView):
    """View a single profile"""
    model = models.Company
    slug_field = 'vat_id'
    
    
class CompanyList(ListView):
    """View all profiles"""
    model = models.Company
    
    # filter via query
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = filters.CompanyFilter(self.request.GET, queryset=self.get_queryset())
        return context
    
    
class CompanyUpdate(UpdateView):
    """Update a company"""
    model = models.Company
    form_class = forms.CompanyForm
    success_url = reverse_lazy('erp_core:company_list')
    
    
class CompanyClone(CreateView):
    """Get object desired from url with record.id and override the object context with it.
    """
    model = models.Company
    form_class = forms.CompanyForm
    success_url = reverse_lazy('erp_core:company_list')
    template_name = 'erp_core/company_clone.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.name = f"{self.object.name}_CLONE"
        self.object.vat_id = 0
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)
    
    
# PRODUCT MANAGEMENT

class ProductCreate(CreateView):
    """Create a new product"""
    model = models.Product
    form_class = forms.ProductForm
    success_url = reverse_lazy('erp_core:product_list') 
    
    
class ProductDetail(DetailView):
    """View a single product"""
    model = models.Product
    slug_field = 'id'
    
    
class ProductList(ListView):
    """View all profiles"""
    model = models.Product
    
    # filter via query
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = filters.ProductFilter(self.request.GET, queryset=self.get_queryset())
        return context
    
    
class ProductUpdate(UpdateView):
    """Update a product"""
    model = models.Product
    form_class = forms.ProductForm
    success_url = reverse_lazy('erp_core:product_list')
    
    
class ProductClone(CreateView):
    """Get object desired from url with record.id and override the object context with it.
    """
    model = models.Product
    form_class = forms.ProductForm
    success_url = reverse_lazy('erp_core:product_list')
    template_name = 'erp_core/product_clone.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.name = f"{self.object.name}_CLONE"
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


# INVOICE MANAGEMENT
    
class InvoiceCreate(CreateView):
    """Create a new invoice"""
    model = models.Invoice
    form_class = forms.InvoiceForm
    success_url = reverse_lazy('erp_core:invoice_list') 
    
    
class InvoiceList(ListView):
    """View all invoices"""
    model = models.Invoice   
        
    # filter via query
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = filters.InvoiceFilter(self.request.GET, queryset=self.get_queryset())
        return context  
    
    
class InvoiceUpdate(UpdateView):
    """Update an invoice"""
    model = models.Invoice
    form_class = forms.InvoiceForm
    success_url = reverse_lazy('erp_core:invoice_list')
    

class InvoiceClone(CreateView):
    """Get object desired from url with record.id and override the object context with it.
    """
    model = models.Invoice
    form_class = forms.InvoiceForm
    success_url = reverse_lazy('erp_core:invoice_list')
    template_name = 'erp_core/invoice_clone.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)
    
    
# PAYMENT MANAGEMENT

class PaymentCreate(CreateView):
    """Create a new payment"""
    model = models.Payment
    form_class = forms.PaymentForm
    success_url = reverse_lazy('erp_core:payment_list') 
    
    
class PaymentList(ListView):
    """View all Payments"""
    model = models.Payment
    
    # filter via query
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = filters.PaymentFilter(self.request.GET, queryset=self.get_queryset())
        return context  
    
    
class PaymentUpdate(UpdateView):
    """Update an Payment"""
    model = models.Payment
    form_class = forms.PaymentForm
    success_url = reverse_lazy('erp_core:payment_list')
    
    
class PaymentClone(CreateView):
    """Get object desired from url with record.id and override the object context with it.
    """
    model = models.Payment
    form_class = forms.PaymentForm
    success_url = reverse_lazy('erp_core:payment_list')
    template_name = 'erp_core/payment_clone.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)
    
    
# PRE-MADE FILTERS

class FilteredView(View):
    """Main page for all the filters"""
    def get(self, request):
        return render(request, 'erp_core/filtered_view.html')


class InvoiceActive(View):
    """Pre-made filter for active invoices"""
    model = models.Invoice
    template_name = 'erp_core/invoice_active.html'
    
    def get(self, request):
        context = self.model.objects.all().filter(kind='ACTIVE')
        return render(request, self.template_name, {'context': context})
    
    
class InvoiceActiveOverdue(View):
    """Pre-made filter for overdue active invoices"""
    model = models.Invoice
    template_name = 'erp_core/invoice_active_overdue.html'
    
    def get(self, request):
        context = self.model.objects.all().filter(kind='ACTIVE', status='UNPAID')
        return render(request, self.template_name, {'context': context})


class InvoicePassive(View):
    """Pre-made filter for passive invoices"""
    model = models.Invoice
    template_name = 'erp_core/invoice_passive.html'
    
    def get(self, request):
        context = self.model.objects.all().filter(kind='PASSIVE')
        return render(request, self.template_name, {'context': context}) 
    
    
class InvoicePassiveOverdue(View):
    """Pre-made filter for overdue active invoices"""
    model = models.Invoice
    template_name = 'erp_core/invoice_passive_overdue.html'
    
    def get(self, request):
        context = self.model.objects.all().filter(kind='PASSIVE', status='UNPAID')
        return render(request, self.template_name, {'context': context})
    
    
class PaymentActive(View):
    """Pre-made filter for active payments"""
    model = models.Payment
    template_name = 'erp_core/payment_active.html'
    
    def get(self, request):
        context = self.model.objects.all().filter(kind='ACTIVE')
        return render(request, self.template_name, {'context': context})


class PaymentPassive(View):
    """Pre-made filter for passive payments"""
    model = models.Payment
    template_name = 'erp_core/payment_passive.html'
    
    def get(self, request):
        context = self.model.objects.all().filter(kind='PASSIVE')
        return render(request, self.template_name, {'context': context})    


# CREDIT MANAGEMENT

class CheckActive(View):
    """View to show the credit balance"""
    template_name = 'erp_core/check_active.html'
    
    def get(self, request):
        context = functions.credit_calculator('ACTIVE')
        return render(request, self.template_name, {'context': context})
    
    
class CheckPassive(View):
    """View to show the credit balance"""
    template_name = 'erp_core/check_passive.html'
    
    def get(self, request):
        context = functions.credit_calculator('PASSIVE')
        return render(request, self.template_name, {'context': context})


# CSV EXPORT

class CsvExport(View):
    """Generate a csv file of the context object"""
    template_name = 'erp_core/csv_export.html'
    
    def get(self, request) -> csv:
        response = HttpResponse(
            content_type='text/csv',
            headers={'Content-Disposition':'attachment; filename="csv_detail.csv"'},
        )
        
        # this allows to scale on many other CSV export just managing the url param
        if 'invoice' in self.request.GET:
            model = models.Invoice.objects.all().values()
        elif 'company' in self.request.GET:
            model = models.Company.objects.all().values()
        elif 'product' in self.request.GET:
            model = models.Product.objects.all().values()
        else:
            raise Http404
        
        writer = csv.writer(response)
        
        for item in model:
            writer.writerow([item])

erp/erp_core/templates/erp_core/company_clone.html
{% extends 'base.html' %}
{% load static %}

{%block title %}
    <title>Clone a company</title>
{% endblock title %}

{% block content %}
    
    <div class="container">
        <div class="col-6">
        <h1>Creating {{ company.name }}</h2>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                {% for item in form %}
                    <div class="form-group mx-auto mb-2">
                        {{ item.label }}</br>
                        {{ item }}
                    </div>
                {% endfor %}
            </div>

            <div class="error-message">
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %} 
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
            {% endif %}
            </div>

            <input type="submit" class="btn btn-info text-light", value="Submit">
            <br><br>
        </form>

    </div>

{% endblock content %}

erp/erp_core/templates/erp_core/company_list bck.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Company List</title>
{% endblock title %}

{% block content %}

    <div class="container">
        <h2>&nbsp;Company list</h2>

        <div class="row">
            <div class="col-8">
                <form action="" method="get">
                    <div class="form-group">
                    {% for item in filter.form %}
                    <div class="form-group mx-auto mb-2">
                        {{ item.label }}</br>
                        {{ item }}
                    </div>
                    {% endfor %}
                    <input type="submit" class="btn btn-info text-light", value="Search">
                    <a href="{% url 'erp_core:company_list' %}" class="btn text-light btn-info">Clean filters</a>
                </form>
                <br><br>
            </div>    
        </div>

            <div class="col-6">
                {% comment %} {% for company in object_list %} {% endcomment %}
                {% if filter.qs is None %}
                    { filter.qs = object_list }
                {% endif %}
                {% for company in filter.qs %} 
                <div class="card m-2">
                    <div class="card-body">
                        <div class="col d-flex">
                            <a href="{% url 'erp_core:company_detail' company.vat_id %}">
                                <h6 class="card-title my-auto">{{ company.name|upper }}</h6>
                            </a>
                        </div>
                        <div class="col">
                            <p class="card-text">
                                {{ company.industry }}
                                <br>
                                {% if company.website %}
                                    <a href="{{ company.website }}" target="_blank">{{ company.website }}</a>
                                {% else %}
                                    <span>No website</span>
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            
        </div>
    </div>
    
{% endblock content %}

erp/erp_core/templates/erp_core/help.html
{% extends 'base.html' %}
{% load static %}

{%block title %}
    <title>Here to help!</title>
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row align-items-start">
        <div class="col">
            <h2>Welcome to sERPent</h2>
            <h3>A full-Python ERP prototype</h3>
            <p>
                This is an ERP template entirely made with Django.<br>
                Here's you have a <a href="{% url 'erp_core:feature' %}">list</a> of all the features.<br>
                Template has been made by <a title="Github profile" href="https://github.com/carloocchiena" target="_blank">Carlo Occhiena</a>.<br>
                Do you need help? (this is not a real email, just for template purpose!)<br>
                <a title="Send an email" href="mailto:helpmail@mail.com">Contact me</a><br>
            </p>
    </div>    
</div>

{% endblock content %}

erp/erp_core/templates/erp_core/home.html
{% extends 'base.html' %}
{% load static %}

{%block title %}
    <title>ERP Home Page</title>
{% endblock title %}

{% block content %}
    
    <div class="container">

        <h1 class="mb-4">Howdy, {{ user.username|title }}.<br>What do you want to do?</h1>
        <div class="row">
            <div class="col-6">
                <div class"btn-group">
                    <a href="{% url 'erp_core:company_create' %}"
                        <button class="menu-btn btn btn-info text-light mb-2">Add a new company</button>
                    </a>

                    <a href="{% url 'erp_core:product_create' %}"
                        <button class="menu-btn btn btn-info text-light mb-2">Add a new product</button>
                    </a>

                    <a href="{% url 'erp_core:invoice_create' %}"
                        <button class="menu-btn btn btn-info text-light mb-2">Add a new invoice</button>
                    </a>

                    <a href="{% url 'erp_core:payment_create' %}"
                        <button class="menu-btn btn btn-info text-light mb-2">Add a new payment</button>
                    </a>

                    <a href="{% url 'erp_core:company_list' %}"
                        <button class="menu-btn btn btn-info text-light mb-2">Company list</button>
                    </a>

                    <a href="{% url 'erp_core:product_list' %}"
                        <button class="menu-btn btn btn-info text-light mb-2">Product list</button>
                    </a>

                    <a href="{% url 'erp_core:invoice_list' %}"
                        <button class="menu-btn btn btn-info text-light mb-2">Invoice list</button>
                    </a>

                    <a href="{% url 'erp_core:payment_list' %}"
                        <button class="menu-btn btn btn-info text-light mb-2">Payment list</button>
                    </a>

                    <a href="{% url 'erp_core:filtered_view' %}"
                        <button class="menu-btn btn btn-info text-light mb-2">Filtered views</button>
                    </a>
                            
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

erp/erp_core/templates/erp_core/invoice_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Invoice List</title>
{% endblock title %}

{% block content %}

    <div class="container">

        <h2>
            &nbsp;Invoice list
            <a href="{% url 'erp_core:csv_export' %}?invoice" class="btn text-light btn-info btn-sm mt-1 float-end">Export to csv</a>
        </h2>

        <div class="row">
            <div class="col-5">
                <h5 class="ms-2">Search via query</h5>
                <form action="" method="get">
                    <div class="row g-3">
                        <div class="col ms-2">
                            {{ filter.form.sender__name__icontains.label }}<br>
                            {{ filter.form.sender__name__icontains }}<br>
                            {{ filter.form.receiver__name__icontains.label }}<br>
                            {{ filter.form.receiver__name__icontains }}<br>
                            {{ filter.form.date__date.label }}<br>
                            {{ filter.form.date__date }}<br>
                            {{ filter.form.number__icontains.label }}<br>
                            {{ filter.form.number__icontains }}<br>
                            {{ filter.form.amount__icontains.label }}<br>
                            {{ filter.form.amount__icontains }}<br>

                        </div>
                        <div class="col ms-2">
                            {{ filter.form.kind__icontains.label }}<br>
                            {{ filter.form.kind__icontains }}<br>
                            {{ filter.form.due_date__date.label }}<br>
                            {{ filter.form.due_date__date }}<br>
                            {{ filter.form.status__icontains.label }}<br>
                            {{ filter.form.status__icontains }}<br>
                            {{ filter.form.notes__icontains.label }}<br>
                            {{ filter.form.notes__icontains }}<br>
                        </div>
                    </div>
                    <br>
                    <input type="submit" class="btn btn-info text-light mx-2", value="Search">
                    <a href="{% url 'erp_core:invoice_list' %}" class="btn text-light btn-info">Clean filters</a>
                </form>
                <br>

                <div class="col-6">
                    {% if filter.qs is None %}
                        { filter.qs = object_list }
                    {% endif %}
                    <p>&nbsp;There are {{ filter.qs.count }} invoices</p>
                    {% for invoice in filter.qs %} 
                    <div class="card m-2">
                        <div class="card-body">
                            <div class="col">
                                <p class="card-text">
                                    <strong>Invoice nr:</strong> {{ invoice.number }}<br>
                                    From: {{ invoice.sender }}<br>
                                    To: {{ invoice.receiver }}<br>
                                    Kind: {{ invoice.kind }}<br>
                                    Amount: {{ invoice.amount }}<br>
                                    Issued: {{ invoice.date|date:"Y-m-d" }}<br>
                                    Due date: {{ invoice.due_date|date:"Y-m-d" }}<br>
                                    Status: {{ invoice.status }}<br>
                                    <a href="{% url 'erp_core:invoice_update' invoice.id %}" class="btn btn-info btn-sm text-light">
                                        Update invoice
                                    </a>
                                    <a href="{% url 'erp_core:invoice_clone' invoice.id %}" class="btn btn-info btn-sm text-light">
                                        Clone
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

erp/erp_core/templates/erp_core/payment_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Payment List</title>
{% endblock title %}

{% block content %}

    <div class="container">

        <h2>&nbsp;Payment list</h2>

        <div class="row">
            <div class="col-5">
                <h5 class="ms-2">Search via query</h5>
                <form action="" method="get">
                    <div class="row g-3">
                        <div class="col ms-2">
                            {{ filter.form.sender__name__icontains.label }}<br>
                            {{ filter.form.sender__name__icontains }}<br>
                            {{ filter.form.receiver__name__icontains.label }}<br>
                            {{ filter.form.receiver__name__icontains }}<br>
                            {{ filter.form.date__date.label }}<br>
                            {{ filter.form.date__date }}<br>

                        </div>
                        <div class="col ms-2">
                            {{ filter.form.amount__icontains.label }}<br>
                            {{ filter.form.amount__icontains }}<br>
                            {{ filter.form.kind__icontains.label }}<br>
                            {{ filter.form.kind__icontains }}<br>
                            {{ filter.form.notes__icontains.label }}<br>
                            {{ filter.form.notes__icontains }}<br>
                        </div>
                    </div>
                    <br>
                    <input type="submit" class="btn btn-info text-light mx-2", value="Search">
                    <a href="{% url 'erp_core:payment_list' %}" class="btn text-light btn-info">Clean filters</a>
                </form>
                <br>

                <div class="col-6">
                    {% if filter.qs is None %}
                        { filter.qs = object_list }
                    {% endif %}
                    <p>&nbsp;There are {{ filter.qs.count }} payments</p>
                    {% for payment in filter.qs %} 
                    <div class="card m-2">
                        <div class="card-body">
                            <div class="col">
                                <p class="card-text">
                                    <strong>Payment nr:</strong> {{ payment.id }}<br>
                                    From: {{ payment.sender }}<br>
                                    To: {{ payment.receiver }}<br>
                                    Kind: {{ payment.kind }}<br>
                                    Amount: {{ payment.amount }}<br>
                                    Issued: {{ payment.date|date:"Y-m-d" }}<br>
                                    <a href="{% url 'erp_core:payment_update' payment.id %}" class="btn btn-info btn-sm text-light">
                                        Update payment
                                    </a>
                                    <a href="{% url 'erp_core:payment_clone' payment.id %}" class="btn btn-info btn-sm text-light">
                                        Clone
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

erp/erp_core/templates/erp_core/product_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Product List</title>
{% endblock title %}

{% block content %}

    <div class="container">
        
        <h2>
            &nbsp;Productlist
            <a href="{% url 'erp_core:csv_export' %}?product" class="btn text-light btn-info btn-sm mt-1 float-end">Export to csv</a>
        </h2>

        <div class="row">
            <div class="col-5">
                <h5 class="ms-2">Search via query</h5>
                <form action="" method="get">
                    <div class="row g-3">
                        <div class="col ms-2">
                            {{ filter.form.name__icontains.label }}<br>
                            {{ filter.form.name__icontains }}<br>
                            {{ filter.form.description__icontains.label }}<br>
                            {{ filter.form.description__icontains }}<br>
                            {{ filter.form.refill.label }}<br>
                            {{ filter.form.refill }}<br>
                        </div>
                    </div>
                    <br>
                    <input type="submit" class="btn btn-info text-light mx-2", value="Search">
                    <a href="{% url 'erp_core:product_list' %}" class="btn text-light btn-info">Clean filters</a>
                </form>
                <br>
                
                <div class="col">
                    {% if filter.qs is None %}
                        { filter.qs = object_list }
                    {% endif %}
                    <p>&nbsp;There are {{ filter.qs.count }} products</p>
                    {% for product in filter.qs %} 
                    <div class="card m-2">
                        <div class="card-body">
                            <div class="col d-flex">
                                <a href="{% url 'erp_core:product_detail' product.id %}">
                                    <h6 class="card-title my-auto">{{ product.name|upper }}</h6>
                                </a>
                            </div>
                            <div class="col">
                                <p class="card-text">
                                    {{ product.description }}<br>
                                    Price: {{ product.price }}<br>
                                    Remaining: {{ product.quantity }}<br>
                                    Refill: {{ product.refill }}
                                    <br><a href="{% url 'erp_core:product_update' product.id %}" class="btn btn-info btn-sm text-light">
                                        Update product
                                    </a>
                                    <a href="{% url 'erp_core:product_clone' product.id %}" class="btn btn-info btn-sm text-light">
                                        Clone
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}